### ISSUE TITLE
Add `u-isShown`

### ISSUE THREAD

**Issue by necolas** [suitcss/utils-state#4]
``` css
.u-isShown {
  display: block !important;
  visibility: visible !important;
}

table.u-isShown {
  display: table !important;
}

tr.u-isShown,
tr.u-isShown {
  display: table-row !important;
}

td.u-isShown,
th.u-isShown {
  display: table-cell !important;
}
```
